CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'rsm_ddrnet23slim_convlstm'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 20

DATASET:
  DATASET: rsm
  ROOT: 'data/RSM'
  TRAIN_SET: 'list/rsm/train.lst'
  TEST_SET: 'list/rsm/val.lst'
  NUM_CLASSES: 5

MODEL:
  NAME: ddrnet_23_slim
  NUM_OUTPUTS: 2
  PRETRAINED: 'pretrained_models/DDRNet23s_imagenet.pth'
  ALIGN_CORNERS: false
  USE_CONVLSTM: true
  CONVLSTM_HIDDEN_DIM: 128

LOSS:
  USE_OHEM: false
  BALANCE_WEIGHTS: [1.0, 1.0, 1.0, 1.0, 1.0]

TRAIN:
  IMAGE_SIZE:
  - 1024
  - 512
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
  SEQUENCE_MODE: true
  SEQUENCE_LEN: 4

TEST:
  IMAGE_SIZE:
  - 1024
  - 512
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 2
  FLIP_TEST: false
  MULTI_SCALE: false
  SCALE_LIST: [1]
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
