CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: 'rsm_ddrnet23slim_convlstm'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 20

DATASET:
  DATASET: rsm
  ROOT: data/
  TEST_SET: 'list/rsm/val_RSMdataset_v2_seq15.lst'
  TRAIN_SET: 'list/rsm/train_RSMdataset_v2_seq15.lst'
  NUM_CLASSES: 5

MODEL:
  NAME: ddrnet_23_slim
  NUM_OUTPUTS: 2
  PRETRAINED: "runs/cityscapes_ddrnet23_slim_640x480/cityscapes/ddrnet23_slim_640x480/checkpoint.pth.tar"
  ALIGN_CORNERS: false
  USE_CONVLSTM: true
  CONVLSTM_HIDDEN_DIM: 128

LOSS:
  USE_OHEM: false
  BALANCE_WEIGHTS: [1.0, 0.4]

TRAIN:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 600
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
  SEQUENCE_MODE: false
  SEQUENCE_LEN: 15
TEST:
  IMAGE_SIZE:
  - 640
  - 480
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  SCALE_LIST: [1]
  #0.5,0.75,1.0,1.25,1.5,1.75
  # MODEL_FILE: "RSM_v2_imagenet_2048_super_classes/rsm/ddrnet23_slim/best.pth"
  OUTPUT_INDEX: 1
